### PR TITLE
Android Build Platform + IL2CPP + ARM64 + New Input System

### PR DESCRIPTION
**Pull request by VoHeLi**
Android Build Platform + IL2CPP + ARM64 + New Input System
IL2CPP Provides better performance for apps running on Android but can make the building slower the first time.

### CODE REVIEW

**Review by Jack-Development — CHANGES_REQUESTED** [review]
1. Git commit messages should be written in the **imperative mood**
e.g.
``This commit will... {Commit message}``
You can see an example [here](https://github.com/git-guides/git-commit)

2. Please check to see if **BurstDebugInformation** should be added to .gitignore as it states "DoNotShip"

Please update these before we merge to main

**Comment by VoHeLi** [comment]
Should be ok now !

**Comment by Jack-Development** [comment]
Please properly read the example that I sent [here](https://github.com/git-guides/git-commit).
Under "Examples of Git Commit", it shows the correct formatting for a Git commit message

**Comment by VoHeLi** [comment]
Ok, sorry for my misunderstanding, could you please check it again and tell me if this is ok?

**Review by Jack-Development — APPROVED** [review]

**Pull request merged**
