### PR TITLE
Merge OrthographicMap Application to main

### PR DESCRIPTION
**Pull request by Jack-Development**
See Pull Request #4

### CODE REVIEW

**Review by VoHeLi — CHANGES_REQUESTED** [review]
Please add the following statements in the documentation to enhance project installation and compilation : 
- Click yes on the box which says that both input systems are not allowed on Android
- Add the change that must be done to the Niantic package code to avoid compile errors

**Comment by Jack-Development** [comment]
> Please add the following statements in the documentation to enhance project installation and compilation :
> 
>     * Click yes on the box which says that both input systems are not allowed on Android
> 
>     * Add the change that must be done to the Niantic package code to avoid compile errors

We are unable to edit the Niantic package code as it is automatically downloaded locally during the import in Unity and not stored within our repository. As such, it would require a pull request to the Niantic Lightship [repository](https://github.com/niantic-lightship/maps-upm).

**Comment by VoHeLi** [comment]
> > Please add the following statements in the documentation to enhance project installation and compilation :
> > ```
> > * Click yes on the box which says that both input systems are not allowed on Android
> > 
> > * Add the change that must be done to the Niantic package code to avoid compile errors
> > ```
> 
> We are unable to edit the Niantic package code as it is automatically downloaded locally during the import in Unity and not stored within our repository. As such, it would require a pull request to the Niantic Lightship [repository](https://github.com/niantic-lightship/maps-upm).

Please add this issue and the fix inside the documentation without changing the code itself in the repo, so it is easier to install. I don't ask to make it build correctly automatically.

**Comment by Jack-Development** [comment]
I have opened a Pull Request with the Niantic Lightship repository to resolve this issue.
[Pull Request #1](https://github.com/niantic-lightship/maps-upm/pull/1)

**Review by VoHeLi — APPROVED** [review]
Ok, adding documentation later

**Pull request merged**
